# Generated by Django 2.1.1 on 2019-06-23 19:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.CharField(max_length=50)),
                ('view_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('content_type', models.ForeignKey(on_delete=True, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
