# Generated by Django 2.1.1 on 2019-06-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='click_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
