# Generated by Django 2.1.1 on 2019-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20190626_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='click_count',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='analytics',
            name='content_type',
            field=models.ForeignKey(blank=True, on_delete=True, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='object_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
