# Generated by Django 2.1.1 on 2019-07-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20190706_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
