# Generated by Django 2.1.1 on 2019-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analytics_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='contenttypes.ContentType'),
        ),
    ]
