# Generated by Django 2.1.1 on 2019-07-07 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0005_auto_20190706_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
