# Generated by Django 2.1.7 on 2019-03-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_seller',
            new_name='is_commerce',
        ),
    ]
