# Generated by Django 2.1.1 on 2019-06-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_resettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='resettoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
