# Generated by Django 2.1.1 on 2019-07-30 21:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0013_auto_20190707_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('user_name', models.CharField(max_length=200)),
                ('tracking_id', models.CharField(max_length=200)),
                ('total_traffic', models.IntegerField(default=0)),
                ('day_expiry', models.IntegerField(default=3)),
                ('shop', models.ForeignKey(on_delete=False, to='shop.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
