# Generated by Django 2.1.1 on 2019-08-01 19:50

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('user_name', models.CharField(max_length=200)),
                ('tracking_id', models.CharField(max_length=200)),
                ('total_traffic', models.IntegerField(default=0)),
                ('day_expiry', models.IntegerField(default=3)),
                ('user', models.OneToOneField(null=True, on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
