# Generated by Django 2.1.7 on 2019-03-16 19:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=40)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
