# Generated by Django 2.1.7 on 2019-05-23 22:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='categories',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
