# Generated by Django 2.1.7 on 2019-03-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_user'),
        ('findit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop_rel',
            field=models.ForeignKey(null=True, on_delete=True, to='shop.Shop'),
        ),
    ]
