# Generated by Django 2.1.7 on 2019-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0002_products_shop_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='source_url',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
