# Generated by Django 2.1.7 on 2019-05-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0004_products_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='genre',
        ),
    ]
