# Generated by Django 2.1.7 on 2019-05-22 15:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0005_remove_products_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='genre',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
