# Generated by Django 2.1.7 on 2019-06-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0008_remove_products_lppo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='converted_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='createdate',
        ),
        migrations.RemoveField(
            model_name='products',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='old_price_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='old_price_digit',
        ),
        migrations.RemoveField(
            model_name='products',
            name='old_price_digit_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='real_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='real_price_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='shop',
        ),
    ]
