# Generated by Django 2.1.1 on 2019-06-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0010_remove_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpicks',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPicks',
        ),
    ]
