# Generated by Django 2.1.1 on 2019-08-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0011_auto_20190614_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shop_slug',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
