# Generated by Django 2.1.1 on 2019-08-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0012_auto_20190826_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
    ]
