# Generated by Django 2.1.1 on 2019-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0013_auto_20190826_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
