# Generated by Django 2.1.7 on 2019-06-07 07:06

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('setting_up', 'setting_up')], max_length=300)),
                ('video_url', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
